/*node {  
    stage('Build') { 
     echo "**** "
     pwd
     echo "**** "

   }
    stage('Test') { 
        // 
    }
    stage('Deploy') { 
        // 
    }
} */

pipeline {
    agent { label 'master' }
    stages {
        stage('build') {
            steps {
                echo "Hello World!"
                bat '''
                    dir
                    cd bat-scripts
                    dir
                    sum.bat
                    
                 '''
            }
        }
    }
}
